#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

from export_descriptor import build_descriptor


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "gen" / "cpp" / "phk" / "v1"
OUT_PATH = OUT_DIR / "manifest.hpp"


def cpp_string(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=True)


def message_fields(descriptor: dict[str, object]) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for proto_file in descriptor.get("files", []):
        for message in proto_file.get("messages", []):
            message_name = str(message.get("name", ""))
            if not message_name:
                continue
            for field in message.get("fields", []):
                field_name = str(field.get("name", ""))
                if field_name:
                    out.append((message_name, field_name))
    return sorted(out)


def render(descriptor: dict[str, object]) -> str:
    fields = message_fields(descriptor)
    fixture = json.loads((ROOT / "fixtures" / "v0_1_minimal_flow.json").read_text(encoding="utf-8"))
    mode_action = fixture.get("battle_mode_action", {})
    battle_snapshot = fixture.get("battle_snapshot", {})
    battle_event = fixture.get("battle_event", {})
    callback = fixture.get("signed_battle_result_callback", {})
    callback_result = callback.get("result", {})
    lines: list[str] = [
        "// Code generated by tools/export_cpp_manifest.py; DO NOT EDIT.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "#include <cstddef>",
        "#include <string_view>",
        "",
        "namespace phk::v1 {",
        "",
        f"inline constexpr std::string_view kDescriptorVersion = {cpp_string(descriptor.get('descriptor_version', ''))};",
        f"inline constexpr std::string_view kPackageName = {cpp_string(descriptor.get('package', ''))};",
        f"inline constexpr int kProtocolVersion = {int(descriptor.get('protocol_version', 0))};",
        f"inline constexpr std::string_view kBusinessApiVersion = {cpp_string(descriptor.get('business_api_version', ''))};",
        f"inline constexpr std::string_view kBattleApiVersion = {cpp_string(descriptor.get('battle_api_version', ''))};",
        f"inline constexpr std::string_view kRulesetVersion = {cpp_string(descriptor.get('ruleset_version', ''))};",
        f"inline constexpr std::string_view kRulesetHash = {cpp_string(descriptor.get('ruleset_hash', ''))};",
        f"inline constexpr std::string_view kSourceDigestSha256 = {cpp_string(descriptor.get('source_digest_sha256', ''))};",
        f"inline constexpr std::string_view kBattleModeActionMatchId = {cpp_string(mode_action.get('match_id', ''))};",
        f"inline constexpr std::string_view kBattleModeActionPlayerId = {cpp_string(mode_action.get('player_id', ''))};",
        f"inline constexpr std::string_view kBattleModeActionActionId = {cpp_string(mode_action.get('action_id', ''))};",
        f"inline constexpr std::string_view kBattleModeActionActionType = {cpp_string(mode_action.get('action_type', ''))};",
        f"inline constexpr std::string_view kBattleModeActionPayloadJson = {cpp_string(mode_action.get('payload_json', ''))};",
        f"inline constexpr std::uint64_t kBattleModeActionTick = {int(mode_action.get('tick', 0))};",
        f"inline constexpr std::uint64_t kBattleModeActionSeq = {int(mode_action.get('seq', 0))};",
        f"inline constexpr std::string_view kBattleSnapshotMatchId = {cpp_string(battle_snapshot.get('match_id', ''))};",
        f"inline constexpr std::uint64_t kBattleSnapshotSnapshotTick = {int(battle_snapshot.get('snapshot_tick', 0))};",
        f"inline constexpr std::string_view kBattleSnapshotSnapshotKind = {cpp_string(battle_snapshot.get('snapshot_kind', ''))};",
        f"inline constexpr std::string_view kBattleSnapshotStateHash = {cpp_string(battle_snapshot.get('state_hash', ''))};",
        f"inline constexpr std::uint64_t kBattleSnapshotEventCursor = {int(battle_snapshot.get('event_cursor', 0))};",
        f"inline constexpr std::string_view kBattleEventMatchId = {cpp_string(battle_event.get('match_id', ''))};",
        f"inline constexpr std::uint64_t kBattleEventCursor = {int(battle_event.get('cursor', 0))};",
        f"inline constexpr std::uint64_t kBattleEventTick = {int(battle_event.get('tick', 0))};",
        f"inline constexpr std::string_view kBattleEventType = {cpp_string(battle_event.get('type', ''))};",
        f"inline constexpr bool kBattleEventServerAuthoritative = {str(bool(battle_event.get('server_authoritative', False))).lower()};",
        f"inline constexpr std::string_view kBattleResultCallbackMatchId = {cpp_string(callback_result.get('match_id', ''))};",
        f"inline constexpr std::string_view kBattleResultCallbackModeId = {cpp_string(callback_result.get('mode_id', ''))};",
        f"inline constexpr std::string_view kBattleResultCallbackResultHash = {cpp_string(callback_result.get('result_hash', ''))};",
        f"inline constexpr std::string_view kBattleResultCallbackReplayId = {cpp_string(callback_result.get('replay_id', ''))};",
        f"inline constexpr std::string_view kBattleResultCallbackRewardProjectionJson = {cpp_string(callback_result.get('reward_projection_json', ''))};",
        f"inline constexpr std::string_view kBattleResultCallbackModeResultJson = {cpp_string(callback_result.get('mode_result_json', ''))};",
        f"inline constexpr std::string_view kBattleResultCallbackSignatureAlg = {cpp_string(callback.get('signature_alg', ''))};",
        f"inline constexpr std::string_view kBattleResultCallbackKeyId = {cpp_string(callback.get('key_id', ''))};",
        f"inline constexpr std::string_view kBattleResultCallbackPublicKeyHex = {cpp_string(callback.get('public_key_hex', ''))};",
        f"inline constexpr std::string_view kBattleResultCallbackSignatureHex = {cpp_string(callback.get('signature_hex', ''))};",
        f"inline constexpr std::string_view kBattleResultCallbackSubmitPath = {cpp_string(callback.get('submit_path', ''))};",
        f"inline constexpr std::string_view kBattleResultCallbackSettlementKey = {cpp_string(callback.get('settlement_key', ''))};",
        f"inline constexpr std::int64_t kBattleResultCallbackSettledAtMs = {int(callback_result.get('settled_at_ms', 0))};",
        "",
        "struct MessageField {",
        "    std::string_view message;",
        "    std::string_view field;",
        "};",
        "",
        f"inline constexpr std::array<MessageField, {len(fields)}> kMessageFields = {{{{",
    ]
    for message_name, field_name in fields:
        lines.append(f"    {{{cpp_string(message_name)}, {cpp_string(field_name)}}},")
    lines.extend(
        [
            "}};",
            "",
            "[[nodiscard]] constexpr bool HasMessageField(std::string_view message, std::string_view field) {",
            "    for (const auto& item : kMessageFields) {",
            "        if (item.message == message && item.field == field) {",
            "            return true;",
            "        }",
            "    }",
            "    return false;",
            "}",
            "",
            "[[nodiscard]] constexpr std::size_t MessageFieldCount(std::string_view message) {",
            "    std::size_t count = 0;",
            "    for (const auto& item : kMessageFields) {",
            "        if (item.message == message) {",
            "            ++count;",
            "        }",
            "    }",
            "    return count;",
            "}",
            "",
            "}  // namespace phk::v1",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    descriptor = build_descriptor()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render(descriptor), encoding="utf-8")
    print(f"exported {OUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
