#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

from export_descriptor import build_descriptor


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "gen" / "cpp" / "phk" / "v1"
OUT_PATH = OUT_DIR / "manifest.hpp"


def cpp_string(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=True)


def message_fields(descriptor: dict[str, object]) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for proto_file in descriptor.get("files", []):
        for message in proto_file.get("messages", []):
            message_name = str(message.get("name", ""))
            if not message_name:
                continue
            for field in message.get("fields", []):
                field_name = str(field.get("name", ""))
                if field_name:
                    out.append((message_name, field_name))
    return sorted(out)


def render(descriptor: dict[str, object]) -> str:
    fields = message_fields(descriptor)
    lines: list[str] = [
        "// Code generated by tools/export_cpp_manifest.py; DO NOT EDIT.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <string_view>",
        "",
        "namespace phk::v1 {",
        "",
        f"inline constexpr std::string_view kDescriptorVersion = {cpp_string(descriptor.get('descriptor_version', ''))};",
        f"inline constexpr std::string_view kPackageName = {cpp_string(descriptor.get('package', ''))};",
        f"inline constexpr int kProtocolVersion = {int(descriptor.get('protocol_version', 0))};",
        f"inline constexpr std::string_view kBusinessApiVersion = {cpp_string(descriptor.get('business_api_version', ''))};",
        f"inline constexpr std::string_view kBattleApiVersion = {cpp_string(descriptor.get('battle_api_version', ''))};",
        f"inline constexpr std::string_view kRulesetVersion = {cpp_string(descriptor.get('ruleset_version', ''))};",
        f"inline constexpr std::string_view kRulesetHash = {cpp_string(descriptor.get('ruleset_hash', ''))};",
        f"inline constexpr std::string_view kSourceDigestSha256 = {cpp_string(descriptor.get('source_digest_sha256', ''))};",
        "",
        "struct MessageField {",
        "    std::string_view message;",
        "    std::string_view field;",
        "};",
        "",
        f"inline constexpr std::array<MessageField, {len(fields)}> kMessageFields = {{{{",
    ]
    for message_name, field_name in fields:
        lines.append(f"    {{{cpp_string(message_name)}, {cpp_string(field_name)}}},")
    lines.extend(
        [
            "}};",
            "",
            "[[nodiscard]] constexpr bool HasMessageField(std::string_view message, std::string_view field) {",
            "    for (const auto& item : kMessageFields) {",
            "        if (item.message == message && item.field == field) {",
            "            return true;",
            "        }",
            "    }",
            "    return false;",
            "}",
            "",
            "[[nodiscard]] constexpr std::size_t MessageFieldCount(std::string_view message) {",
            "    std::size_t count = 0;",
            "    for (const auto& item : kMessageFields) {",
            "        if (item.message == message) {",
            "            ++count;",
            "        }",
            "    }",
            "    return count;",
            "}",
            "",
            "}  // namespace phk::v1",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    descriptor = build_descriptor()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render(descriptor), encoding="utf-8")
    print(f"exported {OUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
