#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path

from export_descriptor import build_descriptor


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "gen" / "go" / "phk" / "v1"
OUT_PATH = OUT_DIR / "manifest.go"


def go_string(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=True)


def go_ident(value: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", value)
    return "".join(part[:1].upper() + part[1:] for part in parts if part)


def message_fields(descriptor: dict[str, object]) -> dict[str, list[str]]:
    out: dict[str, list[str]] = {}
    for proto_file in descriptor.get("files", []):
        for message in proto_file.get("messages", []):
            name = str(message.get("name", ""))
            fields = [str(field.get("name", "")) for field in message.get("fields", []) if field.get("name")]
            if name:
                out[name] = fields
    return dict(sorted(out.items()))


def render(descriptor: dict[str, object]) -> str:
    fields = message_fields(descriptor)
    fixture = json.loads((ROOT / "fixtures" / "v0_1_minimal_flow.json").read_text(encoding="utf-8"))
    mode_action = fixture.get("battle_mode_action", {})
    callback = fixture.get("signed_battle_result_callback", {})
    callback_result = callback.get("result", {})
    lines: list[str] = [
        "// Code generated by tools/export_go_manifest.py; DO NOT EDIT.",
        "package phkv1",
        "",
        "const (",
        f"\tDescriptorVersion = {go_string(descriptor.get('descriptor_version', ''))}",
        f"\tPackageName = {go_string(descriptor.get('package', ''))}",
        f"\tProtocolVersion = {int(descriptor.get('protocol_version', 0))}",
        f"\tBusinessAPIVersion = {go_string(descriptor.get('business_api_version', ''))}",
        f"\tBattleAPIVersion = {go_string(descriptor.get('battle_api_version', ''))}",
        f"\tRulesetVersion = {go_string(descriptor.get('ruleset_version', ''))}",
        f"\tRulesetHash = {go_string(descriptor.get('ruleset_hash', ''))}",
        f"\tSourceDigestSHA256 = {go_string(descriptor.get('source_digest_sha256', ''))}",
        f"\tBattleModeActionMatchID = {go_string(mode_action.get('match_id', ''))}",
        f"\tBattleModeActionPlayerID = {go_string(mode_action.get('player_id', ''))}",
        f"\tBattleModeActionActionID = {go_string(mode_action.get('action_id', ''))}",
        f"\tBattleModeActionActionType = {go_string(mode_action.get('action_type', ''))}",
        f"\tBattleModeActionPayloadJSON = {go_string(mode_action.get('payload_json', ''))}",
        f"\tBattleModeActionTick = {int(mode_action.get('tick', 0))}",
        f"\tBattleModeActionSeq = {int(mode_action.get('seq', 0))}",
        f"\tBattleResultCallbackMatchID = {go_string(callback_result.get('match_id', ''))}",
        f"\tBattleResultCallbackModeID = {go_string(callback_result.get('mode_id', ''))}",
        f"\tBattleResultCallbackResultHash = {go_string(callback_result.get('result_hash', ''))}",
        f"\tBattleResultCallbackReplayID = {go_string(callback_result.get('replay_id', ''))}",
        f"\tBattleResultCallbackRewardProjectionJSON = {go_string(callback_result.get('reward_projection_json', ''))}",
        f"\tBattleResultCallbackModeResultJSON = {go_string(callback_result.get('mode_result_json', ''))}",
        f"\tBattleResultCallbackSignatureAlg = {go_string(callback.get('signature_alg', ''))}",
        f"\tBattleResultCallbackKeyID = {go_string(callback.get('key_id', ''))}",
        f"\tBattleResultCallbackPublicKeyHex = {go_string(callback.get('public_key_hex', ''))}",
        f"\tBattleResultCallbackSignatureHex = {go_string(callback.get('signature_hex', ''))}",
        f"\tBattleResultCallbackSubmitPath = {go_string(callback.get('submit_path', ''))}",
        f"\tBattleResultCallbackSettlementKey = {go_string(callback.get('settlement_key', ''))}",
        f"\tBattleResultCallbackSettledAtMS = {int(callback_result.get('settled_at_ms', 0))}",
        ")",
        "",
        "var MessageFields = map[string][]string{",
    ]
    for message_name, field_names in fields.items():
        joined = ", ".join(go_string(field) for field in field_names)
        lines.append(f"\t{go_string(message_name)}: {{{joined}}},")
    lines.extend(
        [
            "}",
            "",
            "func HasMessageField(messageName string, fieldName string) bool {",
            "\tfor _, field := range MessageFields[messageName] {",
            "\t\tif field == fieldName {",
            "\t\t\treturn true",
            "\t\t}",
            "\t}",
            "\treturn false",
            "}",
            "",
            "func RequiredMessageFields(messageName string) []string {",
            "\tfields := MessageFields[messageName]",
            "\tout := make([]string, len(fields))",
            "\tcopy(out, fields)",
            "\treturn out",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    descriptor = build_descriptor()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render(descriptor), encoding="utf-8")
    print(f"exported {OUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
