#!/usr/bin/env python3
"""Generate the Go danmaku package for Gensoulkyo / tooling.

Sources:
  - proto/phk/v1/danmaku.proto   (authoritative enum names)
  - data/danmaku_kinds.json      (216 bullet kinds)
  - data/danmaku_motions.json    (79 motion primitives)
  - data/player_loadout.json     (52 shots + 13 bombs)

Output:
  - gen/go/phk/v1/danmaku.go     (package phkv1)

The package name matches gen/go/phk/v1/manifest.go; identifier names are prefixed to
avoid collisions with the existing manifest symbols.
"""
from __future__ import annotations

import json
from pathlib import Path

from export_descriptor import PROTO_DIR, parse_proto


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "gen" / "go" / "phk" / "v1"
OUT_PATH = OUT_DIR / "danmaku.go"

KINDS_PATH = ROOT / "data" / "danmaku_kinds.json"
MOTIONS_PATH = ROOT / "data" / "danmaku_motions.json"
LOADOUT_PATH = ROOT / "data" / "player_loadout.json"
PROTO_PATH = PROTO_DIR / "danmaku.proto"


def go_string(value: object) -> str:
    text = str(value)
    out = ['"']
    for ch in text:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def go_member(proto_name: str, prefix: str) -> str:
    stem = proto_name[len(prefix):] if proto_name.startswith(prefix) else proto_name
    parts = []
    for token in stem.split("_"):
        if not token:
            continue
        parts.append(token if token.isdigit() else token[:1].upper() + token[1:].lower())
    return "".join(parts)


def enum_values(proto: dict[str, object], enum_name: str) -> list[tuple[str, int]]:
    for enum in proto.get("enums", []):
        if enum.get("name") == enum_name:
            return [(str(v["name"]), int(v["number"])) for v in enum.get("values", [])]
    raise SystemExit(f"enum {enum_name} not found in {PROTO_PATH.name}")


def unique_members(values: list[tuple[str, int]], prefix: str) -> list[tuple[str, int]]:
    seen: dict[str, int] = {}
    out: list[tuple[str, int]] = []
    for name, value in values:
        member = go_member(name, prefix)
        if member in seen and seen[member] != value:
            member = f"{member}T{value}"
        seen[member] = value
        out.append((member, value))
    return out


def render() -> str:
    proto = parse_proto(PROTO_PATH)
    kinds = json.loads(KINDS_PATH.read_text(encoding="utf-8"))
    motions = json.loads(MOTIONS_PATH.read_text(encoding="utf-8"))
    loadout = json.loads(LOADOUT_PATH.read_text(encoding="utf-8"))

    kind_vals = unique_members(enum_values(proto, "BulletKind"), "BULLET_KIND_")
    motion_vals = unique_members(enum_values(proto, "BulletMotion"), "BULLET_MOTION_")
    family_vals = unique_members(enum_values(proto, "BulletMotionFamily"), "BULLET_MOTION_FAMILY_")
    player_vals = unique_members(enum_values(proto, "PlayerBulletType"), "PLAYER_BULLET_TYPE_")

    lines: list[str] = [
        "// Code generated by tools/export_danmaku_go.py; DO NOT EDIT.",
        "//",
        "// 千夜追忆 (Touhou: Thousand Night Anamnesis) 1.40 弹幕契约 —— 逆向成果移植。",
        "// 仅供自研玩法的服务端权威模拟使用；不包含任何原版美术/音频二进制资源。",
        "package phkv1",
        "",
        "// ---- 场地 / 节拍 ----",
        "const (",
        "\tDanmakuPlayfieldWidth      = 640",
        "\tDanmakuPlayfieldHeight     = 960",
        "\tDanmakuPlayfieldHalfWidth  = 320",
        "\tDanmakuPlayfieldHalfHeight = 480",
        "\tDanmakuTickRateHz          = 60",
        f"\tDanmakuBulletKindCount     = {len(kinds['kinds'])}",
        f"\tDanmakuBulletMotionCount   = {len(motions['motions'])}",
        f"\tDanmakuPlayerShotCount     = {int(loadout['shot_count'])}",
        f"\tDanmakuPlayerBombCount     = {int(loadout['bomb_count'])}",
        ")",
        "",
        "// ---- BulletKind（原版 kEnemyBullet 值，9..224）----",
        "const (",
    ]
    for member, value in kind_vals:
        lines.append(f"\tBulletKind{member} = {value}")
    lines.extend([")", "", "// ---- BulletMotion（原版 bulletFuncN 编号）----", "const ("])
    for member, value in motion_vals:
        lines.append(f"\tBulletMotion{member} = {value}")
    lines.extend([")", "", "// ---- BulletMotionFamily（粗粒度 A..M 归并）----", "const ("])
    for member, value in family_vals:
        lines.append(f"\tBulletMotionFamily{member} = {value}")
    lines.extend([")", "", "// ---- PlayerBulletType（原版 kMyBullet 值，0..83）----", "const ("])
    for member, value in player_vals:
        lines.append(f"\tPlayerBulletType{member} = {value}")
    lines.extend(
        [
            ")",
            "",
            "// ---- 查找表 ----",
            "var BulletKindFrame = map[int32]string{",
        ]
    )
    for item in kinds["kinds"]:
        lines.append(f"\t{int(item['type'])}: {go_string(item['frame_name'])},")
    lines.extend(["}", "", "var BulletKindAtlas = map[int32]string{"])
    for item in kinds["kinds"]:
        lines.append(f"\t{int(item['type'])}: {go_string(item['atlas'])},")
    lines.extend(["}", "", "var BulletKindSpecies = map[int32]string{"])
    for item in kinds["kinds"]:
        lines.append(f"\t{int(item['type'])}: {go_string(item['species'])},")
    lines.extend(["}", "", "var BulletMotionFamilyCode = map[int32]string{"])
    for item in motions["motions"]:
        lines.append(f"\t{int(item['func'])}: {go_string(item.get('family_code', ''))},")
    lines.extend(["}", "", "var BulletMotionSummary = map[int32]string{"])
    for item in motions["motions"]:
        lines.append(f"\t{int(item['func'])}: {go_string(item['family'])},")
    lines.extend(
        [
            "}",
            "",
            "// ---- 自机 loadout（52 射击 + 13 炸弹）----",
            "type PlayerShotSpec struct {",
            "\tName        string",
            "\tCharacter   string",
            "\tMode        string",
            "\tVariant     uint32",
            "\tVolleyCount uint32",
            "\tBulletTypes []uint32",
            "\tAnglesDeg   []float64",
            "\tSpeed       float64",
            "\tMuzzleExpr  string",
            "\tResolved    bool",
            "}",
            "",
            "type PlayerBombSpec struct {",
            "\tName         string",
            "\tCharacter    string",
            "\tTotalFrames  uint32",
            "\tInvulnFrames uint32",
            "\tBulletCount  uint32",
            "\tBulletTypes  []uint32",
            "\tSprites      []string",
            "}",
            "",
            "var PlayerShots = []PlayerShotSpec{",
        ]
    )
    for shot in loadout["shots"]:
        types = ", ".join(str(t) for t in shot["bullet_types"])
        angles = ", ".join(repr(float(a)) for a in shot["angles_deg"])
        speed = shot.get("speed")
        speed_literal = "0" if speed is None else repr(float(speed))
        lines.append(
            "\t{"
            f"Name: {go_string(shot['name'])}, "
            f"Character: {go_string(shot['character'])}, "
            f"Mode: {go_string(shot['mode'])}, "
            f"Variant: {int(shot['variant'])}, "
            f"VolleyCount: {int(shot['volley_count'])}, "
            f"BulletTypes: []uint32{{{types}}}, "
            f"AnglesDeg: []float64{{{angles}}}, "
            f"Speed: {speed_literal}, "
            f"MuzzleExpr: {go_string(shot['muzzle'])}, "
            f"Resolved: {str(bool(shot['resolved'])).lower()}"
            "},"
        )
    lines.extend(["}", "", "var PlayerBombs = []PlayerBombSpec{"])
    for bomb in loadout["bombs"]:
        types = ", ".join(str(t) for t in bomb["bullet_types"])
        sprites = ", ".join(go_string(s) for s in bomb["sprites"])
        lines.append(
            "\t{"
            f"Name: {go_string(bomb['name'])}, "
            f"Character: {go_string(bomb['character'])}, "
            f"TotalFrames: {int(bomb['total_frames'])}, "
            f"InvulnFrames: {int(bomb['invuln_frames'])}, "
            f"BulletCount: {int(bomb['bullet_count'])}, "
            f"BulletTypes: []uint32{{{types}}}, "
            f"Sprites: []string{{{sprites}}}"
            "},"
        )
    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render(), encoding="utf-8", newline="\n")
    print(f"exported {OUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
