#!/usr/bin/env python3
"""Generate the C++ danmaku header for PhK-BattleServer.

Sources:
  - proto/phk/v1/danmaku.proto   (authoritative enum names + message field layout)
  - data/danmaku_kinds.json      (216 bullet kinds: type -> frame/atlas)
  - data/danmaku_motions.json    (79 motion primitives: func -> family)

Output:
  - gen/cpp/phk/v1/danmaku.hpp   (enums + POD structs + lookup tables)

The header is self-contained (standard library only) and lives in the same include
root as gen/cpp/phk/v1/manifest.hpp, so PhK-BattleServer's CMake finds it unchanged.
"""
from __future__ import annotations

import json
from pathlib import Path

from export_descriptor import PROTO_DIR, parse_proto


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "gen" / "cpp" / "phk" / "v1"
OUT_PATH = OUT_DIR / "danmaku.hpp"

KINDS_PATH = ROOT / "data" / "danmaku_kinds.json"
MOTIONS_PATH = ROOT / "data" / "danmaku_motions.json"
LOADOUT_PATH = ROOT / "data" / "player_loadout.json"
PROTO_PATH = PROTO_DIR / "danmaku.proto"

# Coarse family letters A..M -> enum value; '' -> UNCLASSIFIED.
FAMILY_VALUE = {letter: index + 1 for index, letter in enumerate("ABCDEFGHIJKLM")}
UNCLASSIFIED_VALUE = 14


def pascal(token: str) -> str:
    token = token.strip()
    if not token:
        return ""
    if token.isdigit():
        return token
    return token[:1].upper() + token[1:].lower()


def cpp_enum_member(proto_name: str, prefix: str) -> str:
    stem = proto_name[len(prefix):] if proto_name.startswith(prefix) else proto_name
    parts = [pascal(p) for p in stem.split("_") if p]
    return "k" + "".join(parts)


def enum_values(proto: dict[str, object], enum_name: str) -> list[tuple[str, int]]:
    for enum in proto.get("enums", []):
        if enum.get("name") == enum_name:
            return [(str(v["name"]), int(v["number"])) for v in enum.get("values", [])]
    raise SystemExit(f"enum {enum_name} not found in {PROTO_PATH.name}")


def render_enum(enum_name: str, members: list[tuple[str, int]], comment: str | None = None) -> str:
    lines = [f"enum class {enum_name} : std::int32_t {{"]
    if comment:
        for line in comment.splitlines():
            lines.append(f"    // {line}")
    for member, value in members:
        lines.append(f"    {member} = {value},")
    lines.append("};")
    return "\n".join(lines)


def unique_members(values: list[tuple[str, int]], prefix: str) -> list[tuple[str, int]]:
    seen: dict[str, int] = {}
    out: list[tuple[str, int]] = []
    for name, value in values:
        member = cpp_enum_member(name, prefix)
        if member in seen and seen[member] != value:
            member = f"{member}T{value}"
        seen[member] = value
        out.append((member, value))
    return out


def cpp_string(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=True)


def render() -> str:
    proto = parse_proto(PROTO_PATH)
    kinds = json.loads(KINDS_PATH.read_text(encoding="utf-8"))
    motions = json.loads(MOTIONS_PATH.read_text(encoding="utf-8"))
    loadout = json.loads(LOADOUT_PATH.read_text(encoding="utf-8"))

    kind_vals = unique_members(enum_values(proto, "BulletKind"), "BULLET_KIND_")
    motion_vals = unique_members(enum_values(proto, "BulletMotion"), "BULLET_MOTION_")
    family_vals = unique_members(enum_values(proto, "BulletMotionFamily"), "BULLET_MOTION_FAMILY_")
    player_vals = unique_members(enum_values(proto, "PlayerBulletType"), "PLAYER_BULLET_TYPE_")

    kind_member_by_value = {value: member for member, value in kind_vals}
    motion_member_by_value = {value: member for member, value in motion_vals}
    family_member_by_value = {value: member for member, value in family_vals}

    lines: list[str] = [
        "// Code generated by tools/export_danmaku_cpp.py; DO NOT EDIT.",
        "//",
        "// 千夜追忆 (Touhou: Thousand Night Anamnesis) 1.40 弹幕契约 —— 逆向成果移植。",
        "// 仅供自研玩法的服务端权威模拟使用；不包含任何原版美术/音频二进制资源。",
        "// 关键约定：角度单位=度；spawn_x/spawn_y == -1.0 为「跟随发射者」哨兵；",
        "//           运行期坐标用整数 milli (1/1000 px)；确定性 RNG=(seed,tick,pattern,spawn)。",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace phk::v1 {",
        "",
        "// ---- 场地 / 节拍 ----",
        "inline constexpr std::uint32_t kDanmakuPlayfieldWidth = 640;",
        "inline constexpr std::uint32_t kDanmakuPlayfieldHeight = 960;",
        "inline constexpr std::uint32_t kDanmakuPlayfieldHalfWidth = 320;",
        "inline constexpr std::uint32_t kDanmakuPlayfieldHalfHeight = 480;",
        "inline constexpr std::uint32_t kDanmakuTickRateHz = 60;",
        f"inline constexpr std::size_t kBulletKindCount = {len(kinds['kinds'])};",
        f"inline constexpr std::size_t kBulletMotionCount = {len(motions['motions'])};",
        f"inline constexpr std::size_t kPlayerShotCount = {int(loadout['shot_count'])};",
        f"inline constexpr std::size_t kPlayerBombCount = {int(loadout['bomb_count'])};",
        "",
        "// ---- 枚举 ----",
        render_enum(
            "BulletKind",
            kind_vals,
            "值 = 原版 kEnemyBullet 枚举值 (9..224)；kUnspecified=0 为协议占位。\n"
            "分派表原版位于 EnemyBullet::spriteWithFile @ 0xb0a180 (216 x uint16, idx = type-9)。",
        ),
        "",
        render_enum(
            "BulletMotion",
            motion_vals,
            "与原版 EnemyBullet::bulletFuncN 一一对应 (= 运行期状态号 +0x5B4)。\n"
            "kFunc00 是真实运动（初始化/直线），非占位；原版缺失 9/10/49/56/59/68/69。",
        ),
        "",
        render_enum(
            "BulletMotionFamily",
            family_vals,
            "粗粒度运动学族（bullet_motions.family_group 首字母）。",
        ),
        "",
        render_enum(
            "PlayerBulletType",
            player_vals,
            "原版 kMyBullet 值 (0..83)：0..61 自机射击、62..82 炸弹、83 擦弹。\n"
            "命名取自 .so 内实际贴图字符串；重名资源追加 T<NN> 消歧。",
        ),
        "",
        "// ---- 子弹种类查找表 (216) ----",
        "struct BulletKindInfo {",
        "    BulletKind kind;",
        "    std::string_view frame;   // 图集帧名，如 \"kusabi_01\"",
        "    std::string_view atlas;   // 图集名，如 \"bulletlist01\"",
        "    std::string_view species; // 物种名（如 kusabi/kome/heart），由帧名去尾号得到",
        "};",
        "",
        f"inline constexpr std::array<BulletKindInfo, {len(kinds['kinds'])}> kBulletKinds = {{{{",
    ]
    for item in kinds["kinds"]:
        member = kind_member_by_value[int(item["type"])]
        lines.append(
            f"    {{BulletKind::{member}, {cpp_string(item['frame_name'])}, {cpp_string(item['atlas'])}, "
            f"{cpp_string(item['species'])}}},"
        )
    lines.extend(
        [
            "}};",
            "",
            "// ---- 运动学查找表 (79) ----",
            "struct BulletMotionInfo {",
            "    BulletMotion motion;",
            "    BulletMotionFamily family;",
            "    std::string_view family_group;  // 原 family_group 字符串（含 A..M 前缀）",
            "    std::string_view summary;       // 原 family 摘要",
            "};",
            "",
            f"inline constexpr std::array<BulletMotionInfo, {len(motions['motions'])}> kBulletMotions = {{{{",
        ]
    )
    for item in motions["motions"]:
        motion_member = motion_member_by_value[int(item["func"])]
        code = item.get("family_code", "")
        fam_value = FAMILY_VALUE.get(code, UNCLASSIFIED_VALUE)
        family_member = family_member_by_value[fam_value]
        lines.append(
            f"    {{BulletMotion::{motion_member}, BulletMotionFamily::{family_member}, "
            f"{cpp_string(item['family_group'])}, {cpp_string(item['family'])}}},"
        )
    lines.extend(
        [
            "}};",
            "",
            "// ---- 查找辅助 ----",
            "[[nodiscard]] constexpr std::string_view BulletKindFrame(BulletKind kind) {",
            "    for (const auto& item : kBulletKinds) {",
            "        if (item.kind == kind) {",
            "            return item.frame;",
            "        }",
            "    }",
            "    return {};",
            "}",
            "",
            "[[nodiscard]] constexpr std::string_view BulletKindAtlas(BulletKind kind) {",
            "    for (const auto& item : kBulletKinds) {",
            "        if (item.kind == kind) {",
            "            return item.atlas;",
            "        }",
            "    }",
            "    return {};",
            "}",
            "",
            "[[nodiscard]] constexpr std::string_view BulletKindSpecies(BulletKind kind) {",
            "    for (const auto& item : kBulletKinds) {",
            "        if (item.kind == kind) {",
            "            return item.species;",
            "        }",
            "    }",
            "    return {};",
            "}",
            "",
            "[[nodiscard]] constexpr BulletMotionFamily BulletMotionFamilyOf(BulletMotion motion) {",
            "    for (const auto& item : kBulletMotions) {",
            "        if (item.motion == motion) {",
            "            return item.family;",
            "        }",
            "    }",
            "    return BulletMotionFamily::kUnspecified;",
            "}",
            "",
            "// ---- POD 结构 ----",
            "struct DanmakuFieldSpec {",
            "    std::uint32_t width = kDanmakuPlayfieldWidth;",
            "    std::uint32_t height = kDanmakuPlayfieldHeight;",
            "    std::uint32_t half_width = kDanmakuPlayfieldHalfWidth;",
            "    std::uint32_t half_height = kDanmakuPlayfieldHalfHeight;",
            "    std::uint32_t tick_rate_hz = kDanmakuTickRateHz;",
            "};",
            "",
            "// 严格对应原版 96 字节 Enemy::CreateBulletCommand（28 字段，字段偏移与原版一致）。",
            "// spawn_x/spawn_y == -1.0f 为哨兵（跟随发射者坐标）；角度单位=度。",
            "struct BulletSpawnCommand {",
            "    std::int32_t bullet_type = 0;      // +0  BulletKind 值",
            "    std::int32_t frame_index = 0;      // +4",
            "    float spawn_x = -1.0f;             // +8",
            "    float spawn_y = -1.0f;             // +12",
            "    std::uint8_t flag16 = 0;           // +16",
            "    std::uint8_t _pad17[3] = {0, 0, 0};// +17..19",
            "    float base_angle_deg = 0.0f;       // +20",
            "    float f24 = 0.0f;                  // +24",
            "    float f28 = 0.0f;                  // +28",
            "    float f32 = 0.0f;                  // +32",
            "    float f36 = 0.0f;                  // +36",
            "    float f40 = 0.0f;                  // +40",
            "    std::int16_t count = 0;            // +44 本次发射数量（0 -> 直接返回）",
            "    std::int16_t _pad46 = 0;           // +46",
            "    float spread_or_speed = 0.0f;      // +48 张角/速度",
            "    std::int16_t s52 = 0;              // +52",
            "    std::int16_t s54 = 0;              // +54",
            "    std::int16_t s56 = 0;              // +56",
            "    std::int16_t _pad58 = 0;           // +58",
            "    float f60 = 0.0f;                  // +60",
            "    float f64 = 0.0f;                  // +64",
            "    float f68 = 0.0f;                  // +68",
            "    float f72 = 0.0f;                  // +72",
            "    float f76 = 0.0f;                  // +76",
            "    float f80 = 0.0f;                  // +80",
            "    std::int16_t s84 = 0;              // +84",
            "    std::int16_t s86 = 0;              // +86",
            "    std::int16_t s88 = 0;              // +88",
            "    std::int16_t s90 = 0;              // +90",
            "    std::int16_t s92 = 0;              // +92",
            "    std::int16_t s94 = 0;              // +94",
            "};",
            "static_assert(sizeof(BulletSpawnCommand) == 96, \"CreateBulletCommand must be 96 bytes\");",
            "static_assert(offsetof(BulletSpawnCommand, base_angle_deg) == 20, \"layout drift at +20\");",
            "static_assert(offsetof(BulletSpawnCommand, count) == 44, \"layout drift at +44\");",
            "static_assert(offsetof(BulletSpawnCommand, s94) == 94, \"layout drift at +94\");",
            "",
            "// 运行期子弹状态（服务端权威；坐标/速度 = 整数 milli，1/1000 px）。",
            "struct DanmakuBulletState {",
            "    std::string_view bullet_id;",
            "    BulletKind bullet_kind = BulletKind::kUnspecified;",
            "    BulletMotion motion = BulletMotion::kFunc00;",
            "    std::int32_t x_milli = 0;",
            "    std::int32_t y_milli = 0;",
            "    std::int32_t vx_milli = 0;",
            "    std::int32_t vy_milli = 0;",
            "    std::uint32_t life_ticks = 0;",
            "    std::uint32_t radius_milli = 0;",
            "    std::uint32_t age_ticks = 0;",
            "    std::uint32_t func_state = 0;   // 原版 +0x5B4 状态号",
            "    float angle_deg = 0.0f;",
            "    std::string_view owner_enemy_id;",
            "};",
            "",
            "// Boss 时间线的一个构造批次（setBossBullet* 内 frame % period == offset 的一个块）。",
            "struct DanmakuTimelineEntry {",
            "    std::uint32_t phase = 0;",
            "    std::uint32_t sub_phase = 0;",
            "    std::uint32_t sub_phase_2 = 0;",
            "    std::uint32_t period_ticks = 0;",
            "    std::uint32_t phase_offset = 0;",
            "    std::uint32_t node_size_bytes = 0;",
            "    std::uint32_t bullet_count = 0;",
            "    std::uint32_t pattern_node_id = 0;",
            "    float base_angle_deg = 0.0f;",
            "    float spread_deg = 0.0f;",
            "    BulletKind bullet_kind = BulletKind::kUnspecified;",
            "    BulletMotion motion = BulletMotion::kFunc00;",
            "    std::uint32_t sound_effect_id = 0;",
            "    std::string_view angle_expr;",
            "    std::string_view offset_expr;",
            "};",
            "",
            "}  // namespace phk::v1",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render(), encoding="utf-8", newline="\n")
    print(f"exported {OUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
